---
spring:
  profiles: production
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://doenerdb/god_doener
    username: schoener
    password: schoener
  jpa:
    hibernate.ddl-auto: update
 
---

spring:
  profiles: development
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/god_doener
    username: schoener
    password: schoener
  jpa:
    hibernate.ddl-auto: update

