---
spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost/god_doener
    username: schoener
    password: schoener
  jpa:
    hibernate.ddl-auto: none
    show_sql: true
