---
spring:
  profiles: production
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://doener_db/god_doener
    username: schoener
    password: schoener
  jpa:
    hibernate.ddl-auto: update
    show_sql: true
 

---

spring:
  profiles: development
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost/god_doener
    username: schoener
    password: schoener
  jpa:
    hibernate.ddl-auto: update
    show_sql: true    

server:
  port: 9998
  