---
spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://doener_db/god_doener
    username: schoener
    password: schoener
  jpa:
    hibernate.ddl-auto: update
    show_sql: true
server:
  port: 9998
   
  