version: '3.2'
services:
  doenerdb:
    image: ${DOCKER_REPO_URL}/doener/develop/doenerdb:latest
    build: 
        context: doenerdb
        dockerfile: Dockerfile
  doenerapp:
    environment:
        SPRING_PROFILES_ACTIVE: 'production'  
    image: ${DOCKER_REPO_URL}/doener/develop/doenerapp:latest
    build: 
        context: doenerapp
        dockerfile: Dockerfile
    secrets:
        - doenersecret
    ports:
        - "9998:8080"
    healthcheck:
      test: 'curl --fail localhost:8080'
      interval: 5s
      retries: 5
    restart: always
    healthcheck:
        test: ' exit 0 '
    
  reposerver:
    image: ${DOCKER_REPO_URL}/godmbh/reposerver
secrets:
  doenersecret:
    file: secrets/application.yml
