version: '3.2'
services:
  doener_db:
    image: daily.entwicklung.god.de:5000/doener/develop/doener_db:latest
    networks:
        - internal
    build: 
        context: doener_db
        dockerfile: Dockerfile

  doenerapp:
    image: daily.entwicklung.god.de:5000/doener/develop/doener_app:latest
    labels:
#      - "traefik.domain=docker.localhost"
      - traefik.backend=doenerapp
      - traefik.port=8080
      - traefik.docker.network=traefik_default
      #- "traefik.frontend.rule=Host:doenerapp.docker.localhost"
      - traefik.frontend.rule=Host:doener.entwicklung.god.de
    networks:
        - proxy
        - internal
    build: 
        context: doenerapp
        dockerfile: Dockerfile
    secrets:
        - application.yml 
#    healthcheck:
#        test: ["CMD","nc", "-z", "localhost", "8080"]
#        interval: 20s
#        timeout: 10s
#        retries: 10
    healthcheck:
        test: ' exit 0 '
    restart: always
networks:
  internal:
    external: false
  proxy: 
    external:
        name: proxy_traefik_default
