version: '3.2'
services:
  doenerdb:
    image: ${DOCKER_DAILY_REPO_URL}/${DOCKER_NAMESPACE}/${DOCKER_PROJECTNAME}/doenerdb:${DOCKER_IMAGE_VERSION}
    build: 
        context: doenerdb
        dockerfile: Dockerfile
    healthcheck:
        test: /usr/bin/mysql --user=schoener --password=schoener --execute 'SHOW DATABASES;'
        interval: 3s
        timeout: 1s
        retries: 5        
  doenerapp:
    environment:
        SPRING_PROFILES_ACTIVE: 'production'  
    image: ${DOCKER_DAILY_REPO_URL}/${DOCKER_NAMESPACE}/${DOCKER_PROJECTNAME}/doenerapp:${DOCKER_IMAGE_VERSION}
    build: 
        context: doenerapp
        dockerfile: Dockerfile
    secrets:
        - doenersecret
    depends_on:
      - doenerdb
    healthcheck:
      test: 'curl http://127.0.0.1:8080/'
      interval: 5s
      retries: 50      

#  doenerapp-to-go:
#    image: ${DOCKER_DAILY_REPO_URL}/${DOCKER_NAMESPACE}/${DOCKER_PROJECTNAME}/doenerapp-to-go:${DOCKER_IMAGE_VERSION}
#    build: 
#        context: doenerapp-to-go
#        dockerfile: Dockerfile

secrets:
  doenersecret:
    file: secrets/application.yml
