version: '3.2'
services:
  doenerdb:
    image: ${DOCKER_DAILY_REPO_URL}/${DOCKER_NAMESPACE}/${DOCKER_PROJECTNAME}/doenerdb:${DOCKER_IMAGE_VERSION}
    labels:
      - traefik.backend=doenerdb:${DOCKER_IMAGE_VERSION}  
    networks:
        - internal
    build: 
        context: doenerdb
        dockerfile: Dockerfile
    healthcheck:
        test: /usr/bin/mysql --user=schoener --password=schoener --execute 'SHOW DATABASES;'
        interval: 3s
        timeout: 1s
        retries: 5
  doenerapp:
    environment:
        SPRING_PROFILES_ACTIVE: 'production' 
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
          - node.labels.registry==true
    image: ${DOCKER_DAILY_REPO_URL}/${DOCKER_NAMESPACE}/${DOCKER_PROJECTNAME}/doenerapp:${DOCKER_IMAGE_VERSION}
    labels:
      - traefik.backend=doenerapp${DOCKER_IMAGE_VERSION}
      - traefik.port=8080
      - traefik.docker.network=proxy_traefik_default
      - traefik.frontend.rule=Host:${DOCKER_PROJECTNAME}-latest-doenerapp.entwicklung.god.de
    networks:
        - proxy
        - internal
    depends_on:
      - doenerdb
        
    healthcheck:
      test: 'curl http://127.0.0.1:8080/'
      interval: 5s
      retries: 5

networks:
  internal:
    external: false
  proxy: 
    external:   
        name: proxy_traefik_default
secrets:
  doenersecret:
    file: secrets/application.yml
    