version: '3.2'
services:
  doenerdb:
    image: ${DOCKER_DAILY_REPO_URL}/${DOCKER_NAMESPACE}/${DOCKER_PROJECTNAME}/doener_db:${DOCKER_IMAGE_VERSION}
    build: 
        context: doenerdb
        dockerfile: Dockerfile
  doenerapp:
    environment:
        SPRING_PROFILES_ACTIVE: 'production'  
    image: ${DOCKER_DAILY_REPO_URL}/${DOCKER_NAMESPACE}/${DOCKER_PROJECTNAME}/doener_app:${DOCKER_IMAGE_VERSION}
    build: 
        context: doenerapp
        dockerfile: Dockerfile
    secrets:
        - doenersecret
    ports:
        - "9998:8080"
    healthcheck:
      test: 'curl http://127.0.0.1:8080/'
      interval: 5s
      retries: 50
    
  reposerver:
    image: ${DOCKER_REPO_URL}/godmbh/reposerver
secrets:
  doenersecret:
    file: secrets/application.yml
