version: '3.2'
services:
  doenerdb:
    image: daily.entwicklung.god.de:5000/doener/develop/doenerdb:latest
    build: 
        context: doenerdb
        dockerfile: Dockerfile
  doenerapp:
    environment:
        SPRING_PROFILES_ACTIVE: 'production'  
    image: daily.entwicklung.god.de:5000/doener/develop/doenerapp:latest
    build: 
        context: doenerapp
        dockerfile: Dockerfile
    secrets:
        - doener_secret
    ports:
        - "9998:8080"
    healthcheck:
      test: 'nc -z localhost 8080'
      interval: 5s
      retries: 5
    restart: always
  reposerver:
    image: ${DOCKER_REPO_URL}/godmbh/reposerver
secrets:
  doener_secret:
    file: secrets/application.yml
