version: '3.2'
services:
  doenerdb:
    image: reposrv02nexus3.entwicklung.god.de:5000/private/doener/doenerdb:latest
    labels:
      - traefik.backend=doenerdb:latest 
    networks:
        - internal
    build: 
        context: doenerdb
        dockerfile: Dockerfile

  doenerapp:
    environment:
        SPRING_PROFILES_ACTIVE: 'production' 
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
          - node.labels.registry==true
    image: reposrv02nexus3.entwicklung.god.de:5000/private/doener/doenerapp:latest
    labels:
      - traefik.backend=doenerapp:latest
      - traefik.port=8080
      - traefik.docker.network=proxy_traefik_default
      - traefik.frontend.rule=Host:doener.entwicklung.god.de
    networks:
        - proxy
        - internal
#    build: 
#        context: doenerapp
#        dockerfile: Dockerfile
#    healthcheck:
#        test: ["CMD","nc", "-z", "localhost", "8080"]
#        interval: 20s
#        timeout: 10s
#        retries: 10
    depends_on:
      - doenerdb
        
#    healthcheck:
#        test: ' exit 0 '
    restart: always
  
networks:
  internal:
    external: false
  proxy: 
    external:   
        name: proxy_traefik_default
secrets:
  doenersecret:
    file: secrets/application.yml
    