version: '3.2'
services:
  doenerdb:
    image: ${DOCKER_DAILY_REPO_URL}/${DOCKER_NAMESPACE}/${DOCKER_PROJECTNAME}/doenerdb:${DOCKER_IMAGE_VERSION}
    build: 
        context: doenerdb
        dockerfile: Dockerfile
  doenerapp:
    environment:
        SPRING_PROFILES_ACTIVE: 'production'  
    image: ${DOCKER_DAILY_REPO_URL}/${DOCKER_NAMESPACE}/${DOCKER_PROJECTNAME}/doenerapp:${DOCKER_IMAGE_VERSION}
    build: 
        context: doenerapp
        dockerfile: Dockerfile
    secrets:
        - doenersecret
    depends_on:
      - doenerdb
  reposerver:
    image: ${DOCKER_REPO_URL}/godmbh/reposerver
#  doenerapp-to-go:
#    image: ${DOCKER_DAILY_REPO_URL}/${DOCKER_NAMESPACE}/${DOCKER_PROJECTNAME}/doenerapp-to-go:${DOCKER_IMAGE_VERSION}
#    build: 
#        context: doenerapp-to-go
#        dockerfile: Dockerfile

secrets:
  doenersecret:
    file: secrets/application.yml
