version: '3.2'
services:
  doener_db:
    image: daily.entwicklung.god.de:5000/doener/develop/doener_db:latest
    networks:
        - internal
    build: 
        context: doener_db
        dockerfile: Dockerfile
  doenerapp:
    environment:
        SPRING_PROFILES_ACTIVE: 'production'  
    image: daily.entwicklung.god.de:5000/doener/develop/doener_app:latest
    networks:
        - proxy
        - internal    
    build: 
        context: doenerapp
        dockerfile: Dockerfile
    secrets:
        - doener_secret
    ports:
        - "9998:8080"
#    healthcheck:
#      test: 'curl --fail localhost:8080'
#      interval: 5s
#      retries: 5
    restart: always
    healthcheck:
        test: ' exit 0 '
    
  reposerver:
    image: ${DOCKER_REPO_URL}/godmbh/reposerver
secrets:
  doener_secret:
    file: secrets/application.yml
